apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::423333933641:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-156SCI4Y5A6E7
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::423333933641:role/Test-Role
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2020-12-08T13:01:30Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
    manager: vpcLambda
    operation: Update
    time: "2020-12-08T13:01:30Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "904"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 4db6b7f3-3ae6-4171-be64-140da2ff2ae4
